data:
  corpus:                                 
    root: '/home/henryhenrychen/1TB-SSD/Experiments/master-thesis/mapping_asr/GlobalPhone'
    metas: ['meta/German.txt']
    target: 'ipa'
    train_split: 
    batch_size: 16
  text:
    discard_space: True
    vocab_file: 'corpus/de.ipa.txt'

  transfer:
      src_ckpt: ""
      method: "no"
      mapping: ""

hparas:                                   # Experiment hyper-parameters
  valid_step: 
  max_step: 
  tf_start: 1.0
  tf_end: 1.0
  tf_step: 500000
  optimizer: 'Adadelta'
  lr: 
  eps: 0.00000001                         # 1e-8
  lr_scheduler: 'fixed'                   # 'fixed'/'warmup'
  curriculum: 0

